# Model Configuration for Dog Pose Analysis

# YOLOv11-pose model configuration
MODEL_NAME: "yolov11n-pose"
MODEL_INPUT_SIZE: [640, 640]  # Height, Width
CONFIDENCE_THRESHOLD: 0.5
NMS_THRESHOLD: 0.5

# Dog-specific configuration
# Keypoint names for dog pose estimation
KEYPOINT_NAMES: [
    "nose",           # 0
    "left_eye",       # 1
    "right_eye",      # 2
    "left_ear",       # 3
    "right_ear",      # 4
    "left_shoulder",  # 5
    "right_shoulder", # 6
    "left_elbow",     # 7
    "right_elbow",    # 8
    "left_wrist",     # 9
    "right_wrist",    # 10
    "left_hip",       # 11
    "right_hip",      # 12
    "left_knee",      # 13
    "right_knee",     # 14
    "left_ankle",     # 15
    "right_ankle"     # 16
]

# Dog body connections for skeleton visualization
SKELETON_CONNECTIONS: [
    [0, 1], [0, 2],     # nose to eyes
    [1, 3], [2, 4],     # eyes to ears
    [5, 6],             # shoulders
    [5, 7], [7, 9],     # left arm
    [6, 8], [8, 10],    # right arm
    [11, 12],           # hips
    [11, 13], [13, 15], # left leg
    [12, 14], [14, 16], # right leg
    [5, 11], [6, 12]    # shoulders to hips (torso)
]

# Model paths
MODEL_PATH: "./model/yolo/yolov11_pose_dog.onnx"
LABELS_PATH: "./model/yolo/dog_pose_labels.txt"

# Performance configuration
MAX_DETECTIONS: 1